/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PERSON_PB_H_INCLUDED
#define PB_PERSON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Person {
    char name[64];
    int32_t age;
    char email[128];
} Person;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Person_init_default                      {"", 0, ""}
#define Person_init_zero                         {"", 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define Person_name_tag                          1
#define Person_age_tag                           2
#define Person_email_tag                         3

/* Struct field encoding specification for nanopb */
#define Person_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, INT32,    age,               2) \
X(a, STATIC,   SINGULAR, STRING,   email,             3)
#define Person_CALLBACK NULL
#define Person_DEFAULT NULL

extern const pb_msgdesc_t Person_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Person_fields &Person_msg

/* Maximum encoded size of messages (where known) */
#define PERSON_PB_H_MAX_SIZE                     Person_size
#define Person_size                              206

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
